#!/usr/bin/env bash

# Build the mod
# - This is mostly due to the build being incorrect if not done correctly
# - Which is quite frequent, so may as well make a proper bash script for this.

# Get this current directory, to prevent possible problems
DIR=$(dirname "$0")

# Clean up first, can prevent meaningless errors, at the cost of a slight bit more time to build.
$DIR/clean


echo "Building Modules..."
dotnet build $DIR/LenowoTweeks.AllModules/LenowoTweeks.AllModules.csproj -c $1

if [[ "$1" == "Release" ]] then
	OUTPUT=$DIR/output
	mkdir $OUTPUT

	cp -r $DIR/LenowoTweeks.AllModules/bin/Release/net10.0/Files/* $OUTPUT/
	cp $DIR/LenowoTweeks.AllModules/bin/Release/net10.0/LenowoTweeks.All.zip $OUTPUT/LenowoTweeks.All.zip
fi


echo "Building Config Updater..."
dotnet build $DIR/LenowoTweeks.ConfigUpdater/LenowoTweeks.ConfigUpdater.csproj -c $1

echo "Finished Building!"